Add some missing(?) link libraries
This fixes the following build errors in openSUSE Factory:

CMakeFiles/python_module_PyKDE4_dnssd.dir/sip/dnssd/sipdnssdpart2.cpp.o:
In function `meth_DNSSD_ServiceBrowser_resolveHostName':
/home/abuild/rpmbuild/BUILD/pykde4-4.14.3/build/sip/dnssd/sipdnssdpart2.cpp:408:
undefined reference to `QHostAddress::QHostAddress(QHostAddress
const&)'
/home/abuild/rpmbuild/BUILD/pykde4-4.14.3/build/sip/dnssd/sipdnssdpart2.cpp:408:
undefined reference to `QHostAddress::~QHostAddress()'
collect2: error: ld returned 1 exit status
...
CMakeFiles/python_module_PyKDE4_kio.dir/sip/kio/sipkiopart3.cpp.o: In
function `meth_KFilePlacesModel_deviceForIndex':
/home/abuild/rpmbuild/BUILD/pykde4-4.14.3/build/sip/kio/sipkiopart3.cpp:18560:
undefined reference to `Solid::Device::Device(Solid::Device const&)'
/home/abuild/rpmbuild/BUILD/pykde4-4.14.3/build/sip/kio/sipkiopart3.cpp:18560:
undefined reference to `Solid::Device::~Device()'
CMakeFiles/python_module_PyKDE4_kio.dir/sip/kio/sipkiopart4.cpp.o: In
function `meth_KDeviceListModel_deviceForIndex':
/home/abuild/rpmbuild/BUILD/pykde4-4.14.3/build/sip/kio/sipkiopart4.cpp:27090:
undefined reference to `Solid::Device::Device(Solid::Device const&)'
/home/abuild/rpmbuild/BUILD/pykde4-4.14.3/build/sip/kio/sipkiopart4.cpp:27090:
undefined reference to `Solid::Device::~Device()'
collect2: error: ld returned 1 exit status

REVIEW: 127705